language: generic
env:
  - EMACS=emacs24
before_install:
  - if [ "$EMACS" = "emacs24" ]; then
    sudo add-apt-repository -y ppa:cassou/emacs &&
    sudo apt-get update -qq &&
    sudo apt-get install -qq emacs24 emacs24-el texinfo;
    fi
script:
  - make EMACS=$EMACS elc test
